# Generated by Django 6.0.2 on 2026-05-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0002_messagethread_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='area',
            field=models.CharField(choices=[('HEAD', 'Cabeça'), ('FACE', 'Face'), ('NECK', 'Pescoço'), ('SHOULDER', 'Ombro'), ('ARM', 'Braço'), ('UPPER_ARM', 'Braço superior'), ('ELBOW', 'Cotovelo'), ('FOREARM', 'Antebraço'), ('WRIST', 'Pulso'), ('HAND', 'Mão'), ('FINGERS', 'Dedos'), ('CHEST', 'Peito'), ('BACK', 'Costas'), ('UPPER_BACK', 'Costas superiores'), ('LOWER_BACK', 'Lombar'), ('CORE', 'Core'), ('ABDOMEN', 'Abdómen'), ('HIP', 'Anca'), ('GLUTES', 'Glúteos'), ('LEG', 'Perna'), ('THIGH', 'Coxa'), ('HAMSTRINGS', 'Posterior da coxa'), ('QUADRICEPS', 'Quadríceps'), ('KNEE', 'Joelho'), ('CALF', 'Gémeos'), ('ANKLE', 'Tornozelo'), ('FOOT', 'Pé'), ('TOES', 'Dedos do pé'), ('FULL_BODY', 'Corpo inteiro'), ('BALANCE', 'Equilíbrio'), ('MOBILITY', 'Mobilidade geral')], max_length=32),
        ),
    ]
