# Generated by Django 6.0.2 on 2026-05-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0003_alter_exercise_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='description_pt',
            field=models.TextField(blank=True),
        ),
    ]
