# Generated by Django 6.0.2 on 2026-05-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0004_exercise_description_en_exercise_description_pt'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='name_en',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='exercise',
            name='name_pt',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
