# Generated by Django 6.0.2 on 2026-04-06 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PLAN_CREATED', 'Plan created'), ('PLAN_UPDATED', 'Plan updated'), ('PLAN_ITEM_CREATED', 'Plan item created'), ('PLAN_ITEM_UPDATED', 'Plan item updated'), ('PLAN_ITEM_DELETED', 'Plan item deleted'), ('PROGRESS_CREATED', 'Progress created'), ('MESSAGE_SENT', 'Message sent'), ('MEDIA_CREATED', 'Media created'), ('REWARD_REDEEMED', 'Reward redeemed')], db_index=True, max_length=64)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=64)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
