# Generated by Django 6.0.2 on 2026-04-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('PLAN_CREATED', 'Plan created'), ('PLAN_UPDATED', 'Plan updated'), ('PLAN_ITEM_CREATED', 'Plan item created'), ('PLAN_ITEM_UPDATED', 'Plan item updated'), ('PLAN_ITEM_DELETED', 'Plan item deleted'), ('PROGRESS_CREATED', 'Progress created'), ('MESSAGE_SENT', 'Message sent'), ('MEDIA_CREATED', 'Media created'), ('REWARD_REDEEMED', 'Reward redeemed'), ('EXERCISE_CREATED', 'Exercise created'), ('EXERCISE_UPDATED', 'Exercise updated'), ('EXERCISE_DELETED', 'Exercise deleted'), ('THERAPIST_VIEW_PROGRESS', 'Therapist viewed patient progress'), ('PROFILE_UPDATED', 'Profile updated'), ('SETTINGS_UPDATED', 'Settings updated'), ('FAMILY_LINK_CREATED', 'Family link created'), ('FAMILY_LINK_REVOKED', 'Family link revoked'), ('FAMILY_VIEW_PROGRESS', 'Family viewed patient progress'), ('FAMILY_VIEW_MESSAGES', 'Family viewed patient messages'), ('SESSION_CREATED', 'Session created'), ('SESSION_CANCELLED', 'Session cancelled'), ('REPORT_VIEWED', 'Report viewed')], db_index=True, max_length=64),
        ),
    ]
