# Generated by Django 6.0.2 on 2026-04-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_badge_challenge_reward_badgerule_rewardredemption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pointlog',
            name='points',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pointlog',
            name='reason',
            field=models.CharField(db_index=True, default='PROGRESS_LOG', max_length=40),
        ),
    ]
