# Generated by Django 6.0.2 on 2026-05-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_challenge_assigned_patients_challenge_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointlog',
            name='reason',
            field=models.CharField(choices=[('PROGRESS_LOG', 'Progress log'), ('MESSAGE_SENT', 'Message sent'), ('PLAN_ADHERENCE', 'Plan adherence'), ('CHALLENGE_COMPLETE', 'Challenge completed')], db_index=True, default='PROGRESS_LOG', max_length=40),
        ),
    ]
