# Generated by Django 6.0.2 on 2026-04-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PLAN_ASSIGNED', 'Plan assigned'), ('PLAN_UPDATED', 'Plan updated'), ('NEW_MESSAGE', 'New message'), ('RESOURCE_ADDED', 'Resource added'), ('SESSION_SCHEDULED', 'Session scheduled')], db_index=True, max_length=32),
        ),
    ]
