# Generated by Django 6.0.2 on 2026-05-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PLAN_ASSIGNED', 'Plan assigned'), ('PLAN_UPDATED', 'Plan updated'), ('NEW_MESSAGE', 'New message'), ('RESOURCE_ADDED', 'Resource added'), ('SESSION_SCHEDULED', 'Session scheduled'), ('BADGE_UNLOCKED', 'Badge unlocked'), ('REWARD_REDEEMED', 'Reward redeemed'), ('CHALLENGE_COMPLETED', 'Challenge completed')], db_index=True, max_length=32),
        ),
    ]
